### ISSUE TITLE
Rule not working

### ISSUE THREAD

**Issue by andig** [baswenneker/pimatic-ifttt#3]
Using current pimatic I'm getting

```
Could not find an provider that decides next predicate of "IFTTT device is triggered"
```

Trying to create the sample rule from README.

**Comment by baswenneker** [comment]
@andig can you post your config.json?

**Comment by andig** [comment]
@baswenneker you mean the rule? it didn't even get entered using ui. I could retry from config.json if you want?

**Comment by baswenneker** [comment]
Yes, please. I'll look into adding the rule though the UI.

---

Met vriendelijke groet
Bas Wenneker

**Comment by andig** [comment]
It's the same when I hack it into the config:

```
09:29:47.314 [pimatic] Could not parse rule "if IFTTT device is triggered then log "API is triggered"": Could not find an provider that decides next predicate of "IFTTT device is triggered".
09:29:47.434 [pimatic] Error: Could not find an provider that decides next predicate of "IFTTT device is triggered".
09:29:47.434 [pimatic]>    at _parseRuleString.then.rule (C:\andi\htdocs\pimatic-app\rules.coffee:621:23)
09:29:47.434 [pimatic]>    at tryCatch1 (C:\andi\htdocs\pimatic-app\node_modules\pimatic\node_modules\bluebird\js\main\util.js:43:21)
09:29:47.434 [pimatic]>    at Promise$_callHandler [as _callHandler] (C:\andi\htdocs\pimatic-app\node_modules\pimatic\node_modules\bluebird\js\main\promise.js:627:13)
09:29:47.434 [pimatic]>    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (C:\andi\htdocs\pimatic-app\node_modules\pimatic\node_modules\bluebird\js\main\promise.js:641:18)
09:29:47.434 [pimatic]>    at Promise$_settlePromiseAt [as _settlePromiseAt] (C:\andi\htdocs\pimatic-app\node_modules\pimatic\node_modules\bluebird\js\main\promise.js:800:14)
09:29:47.434 [pimatic]>    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (C:\andi\htdocs\pimatic-app\node_modules\pimatic\node_modules\bluebird\js\main\async.js:75:12)
09:29:47.434 [pimatic]>    at Async$consumeFunctionBuffer (C:\andi\htdocs\pimatic-app\node_modules\pimatic\node_modules\bluebird\js\main\async.js:38:14)
09:29:47.434 [pimatic]>    at process._tickCallback (node.js:419:13)
```

This is the config:

```
  "plugins": [
    {
      "plugin": "pimatic-ifttt",
    },
  ...
  "devices": [
    {
      "id": "ifttt",
      "name": "IFTTT device",
      "class": "IFTTTDevice",
    },
  ...
  "rules": [
    {
    "id": "ifttt-test-rule",
    "name": "ifttt-test-rule",
    "rule": "if IFTTT device is triggered then log \"API is triggered\"",
    "active": true,
    "logging": true
    }
  ],
```

Much appreciated, thanks.

**Comment by baswenneker** [comment]
@andig, I just tested the pimatic-ifttt and got everything working without issues. I followed the instructions in the README of https://github.com/baswenneker/vagrant-pimatic-dev and then the README instructions of pimatic-iftttt.

Can you tell me which version of ifttt is installed:

``` bash
cd <pimatic-root-folder>
npm list | grep ifttt
```

If it's not version `0.1.1`, please run:

``` bash
cd <pimatic-root-folder>
npm install pimatic-ifttt
```

**Comment by andig** [comment]
Excuse me, definitely working. Not the slightest idea why it didn't do so last time, please excuse me.

**Comment by baswenneker** [comment]
@andig No problem, I'm glad it's working now!
